# AI Search data plane: index, datasource, skillset, indexer.
#
# These are data-plane-only resources — not ARM resources — so the azurerm provider cannot
# manage them. Each object is PUT against the Search REST API (api-version 2024-07-01) from a
# local-exec provisioner: with the admin API key when one is provided (free tier), otherwise
# via `az rest`, which acquires an Entra ID token for the logged-in principal.
#
# Retrieval is chunk-based: each document is split into overlapping chunks (SplitSkill), each
# chunk is embedded separately (AzureOpenAIEmbeddingSkill), and one index document is written per
# chunk via index projections.
#
# One datasource + one indexer cover the entire documents container, regardless of how many
# topics are configured. The `topic` and `access_level` fields come from blob metadata set at
# upload time (by the in-app document manager, Terraform sample uploads, or --metadata on the
# CLI) and are projected onto every chunk. Index projection mappings can only read nodes from
# the enrichment tree — field-mapping functions like extractTokenAtPosition never reach the
# chunk documents, which is why the folder path alone cannot drive these fields. A blob without
# the metadata matches no access filter and is invisible to every user: fail closed.
#
# Each REST body is precomputed as a single-line JSON string in locals and written to a temp file
# (mktemp) before the call, so concurrent applies never collide on a shared temp path.

locals {
  search_endpoint    = "https://${var.search_name}.search.windows.net"
  search_api_version = "2024-07-01"
  search_resource    = "https://search.azure.com"

  index_name      = "rag-index"
  datasource_name = "rag-datasource"
  skillset_name   = "rag-skillset"
  indexer_name    = "rag-indexer"

  index_body_json = jsonencode(merge(
    {
      name = local.index_name
      fields = [
        # Per-chunk key, auto-generated by index projections. Keyword analyzer because the
        # generated value contains characters the default analyzer would tokenize.
        { name = "chunk_id", type = "Edm.String", key = true, searchable = true, filterable = true, sortable = true, retrievable = true, analyzer = "keyword" },
        { name = "parent_id", type = "Edm.String", filterable = true, retrievable = true, searchable = false },
        { name = "content", type = "Edm.String", searchable = true, retrievable = true, filterable = false },
        { name = "embedding", type = "Collection(Edm.Single)", searchable = true, retrievable = false, stored = false, dimensions = var.embedding_dimensions, vectorSearchProfile = "vector-profile" },
        { name = "file_name", type = "Edm.String", searchable = false, filterable = true, retrievable = true },
        { name = "topic", type = "Edm.String", filterable = true, retrievable = true, searchable = false },
        { name = "access_level", type = "Edm.String", filterable = true, retrievable = true, searchable = false },
        { name = "metadata_storage_path", type = "Edm.String", filterable = false, retrievable = true, searchable = false },
      ]
      vectorSearch = {
        algorithms = [{ name = "hnsw-config", kind = "hnsw", hnswParameters = { m = 4, efConstruction = 400, efSearch = 500, metric = "cosine" } }]
        profiles   = [{ name = "vector-profile", algorithm = "hnsw-config" }]
      }
    },
    var.semantic_enabled ? {
      semantic = {
        configurations = [{ name = "rag-semantic-config", prioritizedFields = { prioritizedContentFields = [{ fieldName = "content" }], prioritizedKeywordsFields = [{ fieldName = "file_name" }] } }]
      }
    } : {}
  ))

  datasource_body_json = jsonencode({
    name        = local.datasource_name
    type        = "azureblob"
    credentials = { connectionString = var.datasource_connection_string }
    container   = { name = var.container_name }
    dataChangeDetectionPolicy = {
      "@odata.type"           = "#Microsoft.Azure.Search.HighWaterMarkChangeDetectionPolicy"
      highWaterMarkColumnName = "metadata_storage_last_modified"
    }
    dataDeletionDetectionPolicy = {
      "@odata.type"         = "#Microsoft.Azure.Search.SoftDeleteColumnDeletionDetectionPolicy"
      softDeleteColumnName  = "IsDeleted"
      softDeleteMarkerValue = "true"
    }
  })

  skillset_body_json = jsonencode({
    name        = local.skillset_name
    description = "Split documents into chunks and embed each chunk"
    skills = [
      {
        "@odata.type"       = "#Microsoft.Skills.Text.SplitSkill"
        name                = "split-skill"
        context             = "/document"
        textSplitMode       = "pages"
        maximumPageLength   = var.chunk_max_chars
        pageOverlapLength   = var.chunk_overlap_chars
        defaultLanguageCode = "en"
        inputs              = [{ name = "text", source = "/document/content" }]
        outputs             = [{ name = "textItems", targetName = "pages" }]
      },
      merge(
        {
          "@odata.type" = "#Microsoft.Skills.Text.AzureOpenAIEmbeddingSkill"
          name          = "embedding-skill"
          description   = "Embeds each chunk using Azure OpenAI ${var.embedding_model}"
          context       = "/document/pages/*"
          resourceUri   = var.openai_endpoint
          deploymentId  = var.embedding_deployment
          modelName     = var.embedding_model
          dimensions    = var.embedding_dimensions
          inputs        = [{ name = "text", source = "/document/pages/*" }]
          outputs       = [{ name = "embedding", targetName = "embedding" }]
        },
        var.openai_api_key != "" ? { apiKey = var.openai_api_key } : {}
      ),
    ]
    indexProjections = {
      selectors = [
        {
          targetIndexName    = local.index_name
          parentKeyFieldName = "parent_id"
          sourceContext      = "/document/pages/*"
          mappings = [
            { name = "content", source = "/document/pages/*" },
            { name = "embedding", source = "/document/pages/*/embedding" },
            { name = "file_name", source = "/document/metadata_storage_name" },
            { name = "topic", source = "/document/topic" },
            { name = "access_level", source = "/document/access_level" },
            { name = "metadata_storage_path", source = "/document/metadata_storage_path" },
          ]
        }
      ]
      parameters = { projectionMode = "skipIndexingParentDocuments" }
    }
  })

  indexer_body_json = jsonencode({
    name            = local.indexer_name
    dataSourceName  = local.datasource_name
    skillsetName    = local.skillset_name
    targetIndexName = local.index_name
    schedule        = { interval = "PT1H" }
    parameters = { configuration = merge(
      { dataToExtract = "contentAndMetadata", parsingMode = "default" },
      # In a private-network deployment the indexer must run in the search service's private
      # execution environment so it reaches Storage (blob reads) and Azure OpenAI (embedding skill)
      # over the shared private links. Left in the default (multi-tenant) environment it hits the
      # firewalled backends over the public path, which Search surfaces as a misleading
      # "Credentials provided in the connection string are invalid or have expired" error and
      # indexes zero documents. Unset (standard) for the all-public free/dev configs.
      var.execution_environment != null ? { executionEnvironment = var.execution_environment } : {}
    ) }
  })

  # Shared bash helper: PUT a JSON body with the admin key when provided, Entra ID otherwise.
  put_object = <<-EOT
    put_object() {
      local url="$1" body_file="$2"
      if [ -n "$SEARCH_ADMIN_KEY" ]; then
        curl -sf -X PUT "$url" \
          -H 'Content-Type: application/json' \
          -H "api-key: $SEARCH_ADMIN_KEY" \
          --data-binary @"$body_file"
      else
        az rest --method put \
          --url "$url" \
          --resource "${local.search_resource}" \
          --headers "Content-Type=application/json" \
          --body @"$body_file"
      fi
    }
  EOT
}

resource "terraform_data" "search_index" {
  triggers_replace = [
    local.search_endpoint,
    local.index_body_json,
  ]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -e
      SEARCH_ADMIN_KEY='${var.admin_api_key}'
      ${local.put_object}
      TMP=$(mktemp)
      cat > "$TMP" <<'BODY'
      ${local.index_body_json}
      BODY
      put_object "${local.search_endpoint}/indexes/${local.index_name}?api-version=${local.search_api_version}" "$TMP"
      rm -f "$TMP"
    EOT
  }
}

resource "terraform_data" "datasource" {
  triggers_replace = [
    local.search_endpoint,
    local.datasource_body_json,
  ]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -e
      SEARCH_ADMIN_KEY='${var.admin_api_key}'
      ${local.put_object}
      TMP=$(mktemp)
      cat > "$TMP" <<'BODY'
      ${local.datasource_body_json}
      BODY
      put_object "${local.search_endpoint}/datasources/${local.datasource_name}?api-version=${local.search_api_version}" "$TMP"
      rm -f "$TMP"
    EOT
  }
}

resource "terraform_data" "skillset" {
  triggers_replace = [
    local.search_endpoint,
    local.skillset_body_json,
  ]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -e
      SEARCH_ADMIN_KEY='${var.admin_api_key}'
      ${local.put_object}
      TMP=$(mktemp)
      cat > "$TMP" <<'BODY'
      ${local.skillset_body_json}
      BODY
      put_object "${local.search_endpoint}/skillsets/${local.skillset_name}?api-version=${local.search_api_version}" "$TMP"
      rm -f "$TMP"
    EOT
  }

  depends_on = [terraform_data.search_index]
}

resource "terraform_data" "indexer" {
  triggers_replace = [
    terraform_data.skillset.id,
    terraform_data.datasource.id,
    local.indexer_body_json,
  ]

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -e
      SEARCH_ADMIN_KEY='${var.admin_api_key}'
      ${local.put_object}
      TMP=$(mktemp)
      cat > "$TMP" <<'BODY'
      ${local.indexer_body_json}
      BODY
      put_object "${local.search_endpoint}/indexers/${local.indexer_name}?api-version=${local.search_api_version}" "$TMP"
      rm -f "$TMP"
    EOT
  }

  depends_on = [
    terraform_data.search_index,
    terraform_data.skillset,
    terraform_data.datasource,
  ]
}
