# Access-control contract for Aria.
#
# Pure logic, no Azure dependencies — this is the security boundary, so it is unit-tested
# in isolation (see tests/test_access.py). Everything here derives from:
#   1. The user's Entra app roles, read from the signed Easy Auth principal header.
#   2. The deploy-time topics map, the ordered tiers list, and public_tier_mode.
#
# Tiers are configurable per deployment (the TIERS app setting). They are an ordered list, most-open
# first — tiers[0] is the base/open tier (e.g. "public"). A higher tier implies every lower tier.
#
# Role value contract (generated by modules/identity): "<slug>.<Tier>.<Action>", e.g.
#   hr.Internal.Read   -> read the "internal" tier and every tier below it, in topic "hr"
#   hr.Content.Admin   -> manage docs (upload/delete/reindex) + read every tier in "hr"
#   hr.Public.Read     -> read the base tier in "hr" (only minted in role_required mode)
# The Reader role name for a tier is the tier name title-cased + ".Read" (matches Terraform title()).
#
# The search filter is always scoped to a single topic AND a set of tiers, so a role for topic A can
# never return topic B content — that property is what the regression tests assert.

import base64
import json

# Fallback when the TIERS app setting is absent (kept in sync with the Terraform default).
DEFAULT_TIERS = ["general", "internal"]


def parse_topics(raw: str) -> dict[str, str]:
    # TOPICS app setting is the jsonencode'd terraform map (slug -> display name).
    try:
        data = json.loads(raw) if raw else {}
    except (ValueError, TypeError):
        return {}
    return {k: v for k, v in data.items() if isinstance(k, str) and isinstance(v, str)}


def parse_tiers(raw: str) -> list[str]:
    # TIERS app setting is the jsonencode'd terraform list (ordered, most-open first).
    try:
        data = json.loads(raw) if raw else []
    except (ValueError, TypeError):
        return list(DEFAULT_TIERS)
    tiers = [t for t in data if isinstance(t, str) and t]
    return tiers or list(DEFAULT_TIERS)


def get_user_roles(principal_header: str) -> set[str]:
    # Easy Auth injects X-MS-CLIENT-PRINCIPAL as base64 JSON of the user's claims. The platform
    # signs it, so it cannot be forged by callers. Returns the raw role values (e.g. "hr.Internal.Read").
    if not principal_header:
        return set()
    try:
        padded = principal_header + "=" * (-len(principal_header) % 4)
        decoded = json.loads(base64.b64decode(padded))
        role_typ = decoded.get(
            "role_typ",
            "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
        )
        claims = decoded.get("claims", [])
        return {c["val"] for c in claims if c.get("typ") in (role_typ, "roles")}
    except Exception:
        return set()


def _topic_actions(roles: set[str], slug: str) -> set[str]:
    # The action part of every role the user holds for this topic, e.g. {"Internal.Read", "Content.Admin"}.
    prefix = f"{slug}."
    return {role[len(prefix):] for role in roles if role.startswith(prefix)}


def _reader_action(tier: str) -> str:
    # Reader role action for a tier, matching the role values minted by Terraform (title() + ".Read").
    return f"{tier.title()}.Read"


def allowed_levels(roles: set[str], slug: str, tiers: list[str], public_tier_mode: str) -> list[str]:
    # Hierarchical resolution of which tiers the user may read in this topic.
    # Returns an ordered subset of `tiers`; empty means no access at all.
    actions = _topic_actions(roles, slug)
    granted: set[str] = set()

    # Content.Admin can read every configured tier.
    if "Content.Admin" in actions:
        granted |= set(tiers)

    # A Reader role for a tier grants that tier and every tier below it (lower index = more open).
    for i, tier in enumerate(tiers):
        if _reader_action(tier) in actions:
            granted |= set(tiers[: i + 1])

    # In all_users mode every authenticated employee can see the base tier without any role.
    if public_tier_mode == "all_users" and tiers:
        granted.add(tiers[0])

    return [tier for tier in tiers if tier in granted]


def can_access_topic(roles: set[str], slug: str, tiers: list[str], public_tier_mode: str) -> bool:
    return bool(allowed_levels(roles, slug, tiers, public_tier_mode))


def accessible_topics(roles: set[str], topics: dict[str, str], tiers: list[str], public_tier_mode: str) -> dict[str, str]:
    # The topics a user may see at all, for the landing page and navigation.
    return {
        slug: display
        for slug, display in topics.items()
        if can_access_topic(roles, slug, tiers, public_tier_mode)
    }


def build_search_filter(roles: set[str], slug: str, tiers: list[str], public_tier_mode: str) -> str | None:
    # Server-side OData filter for AI Search. None means "no access" — the caller must refuse,
    # never query unfiltered. Slug is a validated topic key (see callers), not free user input.
    levels = allowed_levels(roles, slug, tiers, public_tier_mode)
    if not levels:
        return None
    level_clause = " or ".join(f"access_level eq '{level}'" for level in levels)
    return f"topic eq '{slug}' and ({level_clause})"


def can_admin_topic(roles: set[str], slug: str) -> bool:
    return "Content.Admin" in _topic_actions(roles, slug)


def admin_topics(roles: set[str], topics: dict[str, str]) -> dict[str, str]:
    # The topics a user may manage in the document manager.
    return {slug: display for slug, display in topics.items() if can_admin_topic(roles, slug)}
